language: python
dist: xenial
sudo: yes
python:
    - "2.7"
    - "3.6"
    - "3.7"

install: 
    - sudo apt-get update
    - sudo apt-get install ccache gcc
    - sudo apt-get install libopenmpi-dev openmpi-bin liblapack-dev
    - pip install numpy scipy mpi4py cython
    - git submodule update --init --recursive
    - cd adpy && pip install . && cd ..
    - make
    - pip install .
    - ./install_deps.sh

script: 
    - tests/run_tests.sh
