#ifndef CODE_H
#define CODE_H
#include "common.hpp"
void Function_primitive(int n, const scalar* Tensor_19, const scalar* Tensor_17, const scalar* Tensor_18, scalar* Tensor_20, scalar* Tensor_30, scalar* Tensor_28);
void Function_primitive_grad(int n, const scalar* Tensor_19, const scalar* Tensor_17, const scalar* Tensor_18, const scalar* Tensor_31, const scalar* Tensor_32, const scalar* Tensor_33, scalar* Tensor_34, scalar* Tensor_35, scalar* Tensor_36);
void Function_grad(int n, const scalar* Tensor_37, const scalar* Tensor_38, const scalar* Tensor_39, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_70, scalar* Tensor_77, scalar* Tensor_84);
void Function_grad_grad(int n, const scalar* Tensor_37, const scalar* Tensor_38, const scalar* Tensor_39, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_85, const scalar* Tensor_86, const scalar* Tensor_87, scalar* Tensor_88, scalar* Tensor_89, scalar* Tensor_90, scalar* Tensor_91, scalar* Tensor_92, scalar* Tensor_93, scalar* Tensor_94, scalar* Tensor_95, scalar* Tensor_96, scalar* Tensor_97, scalar* Tensor_98, scalar* Tensor_99, scalar* Tensor_100);
void Function_coupledGrad(int n, const scalar* Tensor_101, const scalar* Tensor_102, const scalar* Tensor_103, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_131, scalar* Tensor_135, scalar* Tensor_139);
void Function_coupledGrad_grad(int n, const scalar* Tensor_101, const scalar* Tensor_102, const scalar* Tensor_103, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_140, const scalar* Tensor_141, const scalar* Tensor_142, scalar* Tensor_143, scalar* Tensor_144, scalar* Tensor_145, scalar* Tensor_146, scalar* Tensor_147, scalar* Tensor_148, scalar* Tensor_149, scalar* Tensor_150, scalar* Tensor_151, scalar* Tensor_152, scalar* Tensor_153, scalar* Tensor_154, scalar* Tensor_155);
void Function_boundaryGrad(int n, const scalar* Tensor_156, const scalar* Tensor_157, const scalar* Tensor_158, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_165, scalar* Tensor_169, scalar* Tensor_173);
void Function_boundaryGrad_grad(int n, const scalar* Tensor_156, const scalar* Tensor_157, const scalar* Tensor_158, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_174, const scalar* Tensor_175, const scalar* Tensor_176, scalar* Tensor_177, scalar* Tensor_178, scalar* Tensor_179, scalar* Tensor_180, scalar* Tensor_181, scalar* Tensor_182, scalar* Tensor_183, scalar* Tensor_184, scalar* Tensor_185, scalar* Tensor_186, scalar* Tensor_187, scalar* Tensor_188, scalar* Tensor_189);
void Function_flux(int n, const scalar* Tensor_190, const scalar* Tensor_191, const scalar* Tensor_192, const scalar* Tensor_193, const scalar* Tensor_194, const scalar* Tensor_195, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_512, scalar* Tensor_518, scalar* Tensor_524, scalar* Tensor_537);
void Function_flux_grad(int n, const scalar* Tensor_190, const scalar* Tensor_191, const scalar* Tensor_192, const scalar* Tensor_193, const scalar* Tensor_194, const scalar* Tensor_195, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_538, const scalar* Tensor_539, const scalar* Tensor_540, const scalar* Tensor_541, scalar* Tensor_542, scalar* Tensor_543, scalar* Tensor_544, scalar* Tensor_545, scalar* Tensor_546, scalar* Tensor_547, scalar* Tensor_548, scalar* Tensor_549, scalar* Tensor_550, scalar* Tensor_551, scalar* Tensor_552, scalar* Tensor_553, scalar* Tensor_554, scalar* Tensor_555, scalar* Tensor_556, scalar* Tensor_557);
void Function_characteristicFlux(int n, const scalar* Tensor_558, const scalar* Tensor_559, const scalar* Tensor_560, const scalar* Tensor_561, const scalar* Tensor_562, const scalar* Tensor_563, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_832, scalar* Tensor_835, scalar* Tensor_838, scalar* Tensor_849);
void Function_characteristicFlux_grad(int n, const scalar* Tensor_558, const scalar* Tensor_559, const scalar* Tensor_560, const scalar* Tensor_561, const scalar* Tensor_562, const scalar* Tensor_563, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_850, const scalar* Tensor_851, const scalar* Tensor_852, const scalar* Tensor_853, scalar* Tensor_854, scalar* Tensor_855, scalar* Tensor_856, scalar* Tensor_857, scalar* Tensor_858, scalar* Tensor_859, scalar* Tensor_860, scalar* Tensor_861, scalar* Tensor_862, scalar* Tensor_863, scalar* Tensor_864, scalar* Tensor_865, scalar* Tensor_866, scalar* Tensor_867, scalar* Tensor_868, scalar* Tensor_869);
void Function_coupledFlux(int n, const scalar* Tensor_870, const scalar* Tensor_871, const scalar* Tensor_872, const scalar* Tensor_873, const scalar* Tensor_874, const scalar* Tensor_875, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_1189, scalar* Tensor_1192, scalar* Tensor_1195, scalar* Tensor_1206);
void Function_coupledFlux_grad(int n, const scalar* Tensor_870, const scalar* Tensor_871, const scalar* Tensor_872, const scalar* Tensor_873, const scalar* Tensor_874, const scalar* Tensor_875, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_1207, const scalar* Tensor_1208, const scalar* Tensor_1209, const scalar* Tensor_1210, scalar* Tensor_1211, scalar* Tensor_1212, scalar* Tensor_1213, scalar* Tensor_1214, scalar* Tensor_1215, scalar* Tensor_1216, scalar* Tensor_1217, scalar* Tensor_1218, scalar* Tensor_1219, scalar* Tensor_1220, scalar* Tensor_1221, scalar* Tensor_1222, scalar* Tensor_1223, scalar* Tensor_1224, scalar* Tensor_1225, scalar* Tensor_1226);
void Function_boundaryFlux(int n, const scalar* Tensor_1227, const scalar* Tensor_1228, const scalar* Tensor_1229, const scalar* Tensor_1230, const scalar* Tensor_1231, const scalar* Tensor_1232, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, scalar* Tensor_1279, scalar* Tensor_1282, scalar* Tensor_1285, scalar* Tensor_1296);
void Function_boundaryFlux_grad(int n, const scalar* Tensor_1227, const scalar* Tensor_1228, const scalar* Tensor_1229, const scalar* Tensor_1230, const scalar* Tensor_1231, const scalar* Tensor_1232, const scalar* Tensor_0, const scalar* Tensor_1, const scalar* Tensor_2, const scalar* Tensor_3, const scalar* Tensor_4, const scalar* Tensor_5, const scalar* Tensor_6, const scalar* Tensor_7, const integer* Tensor_8, const integer* Tensor_9, const scalar* Tensor_1297, const scalar* Tensor_1298, const scalar* Tensor_1299, const scalar* Tensor_1300, scalar* Tensor_1301, scalar* Tensor_1302, scalar* Tensor_1303, scalar* Tensor_1304, scalar* Tensor_1305, scalar* Tensor_1306, scalar* Tensor_1307, scalar* Tensor_1308, scalar* Tensor_1309, scalar* Tensor_1310, scalar* Tensor_1311, scalar* Tensor_1312, scalar* Tensor_1313, scalar* Tensor_1314, scalar* Tensor_1315, scalar* Tensor_1316);
#endif
